### ISSUE TITLE
fails to work on imgur galleries with different extensions

### ISSUE THREAD

**Issue by tek0011** [jtara1/imgur-downloader#1]
Will not work on a imgur gallery with the following ext:

filename.jpg?2

**Comment by jtara1** [comment]
Could you link me to the imgur url with multiple extensions?

**Comment by tek0011** [comment]
I don't have examples anymore, but I patched it by changing regex:

https://github.com/jtara1/imgur_downloader/blob/master/imgurdownloader.py#L143

from

`self.imageIDs = re.findall('.*?"hash":"([a-zA-Z0-9]+)".*?"ext":"(\.[a-zA-Z0-9]+)".*?', search.group(0))`

to

`self.imageIDs = re.findall('.*?"hash":"([a-zA-Z0-9]+)".*?"ext":"(\.[a-zA-Z0-9?]+)".*?', search.group(0))`

added ? to "ext" [set] 


However, the script still shits the bed on 404s..

**Comment by jtara1** [comment]
Oh so `.jpg?2` was the exact image extension that was matched? I wouldn't expect imgur to have this extension as I don't think it's even a valid file extension.

By the way if you used the script via command line then there may be additional bugs since I haven't touched the command line part of the script at all.

**Comment by tek0011** [comment]
> so .jpg?2 was the exact image extension that was matched?

Yes.  I have seen it 1-2 times out of probably ~ 20,000.  This was using the class form, no cli.   Now to fix the 404 exceptions.
