### ISSUE TITLE
pip install gives error..

### ISSUE THREAD

**Issue by Zachary24** [jtara1/imgur-downloader#20]
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bv/2pw80_r535j10nqy91l3p1cw0000gn/T/pip-install-yjsemuse/imgur-downloader/

tried in python 2.7 and 3.7

**Comment by jtara1** [comment]
what OS are you using?

try 

`pip3 install -U --user imgur-downloader`
`pip2 install -U --user imgur-downloader`

**Comment by jtara1** [comment]
I'm getting a successful install using python 2.7 that's installed system wide 

I'm getting same error as you when I use a locally installed version of python (3.5) (ie: virtualenv) I'm using pyenv I think

**Comment by jtara1** [comment]
It installed just fine after downloading the compressed module (or repo?), deleting the setup.cfg then `sudo python3 setup.py install`

It's been so long since I built up my config stuff for making module pip installable, I don't remember what setup.cfg is for and a quick google search makes it seem like an alternative to doing the same stuff I do in setup.py https://gist.github.com/althonos/6914b896789d3f2078d1e6237642c35c

But, now I'm having an issue with the global cli entry point becoming a null reference when I installed this module using sys wide python 3.7, uninstalled it, installed this module using a locally installed version of python (3.5). 

I'm ready to make js my main language

**Comment by jtara1** [comment]
my on-going setup.py creates setup.cfg if not found and does other stuff with it so ill fix & close this shortly
